In [1]:
from dotenv import load_dotenv
import boto3
from pathlib import Path
import pandas as pd

load_dotenv()  # reads .env, sets env variables

s3 = boto3.client("s3")
bucket_name = "weather-data-eng" #bucket_name

l3y_avg_df = pd.read_csv(s3.get_object(
    Bucket=bucket_name,
    Key="gold/weather/fact_weather_l3y_avg.csv")['Body'])

monthly_by_year_df = pd.read_csv(s3.get_object(
    Bucket=bucket_name,
    Key="gold/weather/fact_weather_monthly_by_year.csv")['Body'])

In [2]:
l3y_avg_df.head(10)

,city,month,min_temperature_celsius,max_temperature_celsius,avg_temperature_celsius,avg_uv_index,avg_daily_sunshine_seconds,avg_daily_rainfall_mm
0,guangzhou,1,2.6,27.3,16.077733,1.228763,30071.753441,0.274194
1,guangzhou,3,7.0,33.3,20.043324,1.467876,23342.699140,2.538710
2,guangzhou,9,21.6,38.2,27.884259,1.735602,29336.631667,13.353333
3,guangzhou,12,3.9,29.3,16.934991,1.097424,27985.813011,0.381720
4,guangzhou,10,16.0,36.4,25.440636,1.505668,29786.803011,2.410753
5,guangzhou,5,17.2,36.0,25.879525,1.618392,24608.604731,8.024731
6,guangzhou,4,11.1,34.4,24.506204,1.789745,26108.187000,10.131111
7,guangzhou,7,24.0,37.4,28.875269,2.102907,34294.227661,8.024194
8,guangzhou,2,5.3,30.2,17.718824,1.270172,22404.613059,0.984706
9,guangzhou,11,10.5,31.0,20.805417,1.221644,27535.395111,0.822222

In [3]:
monthly_by_year_df.head(10)

,city,month_year,min_temperature_celsius,max_temperature_celsius,avg_temperature_celsius,avg_uv_index,avg_daily_sunshine_seconds,avg_daily_rainfall_mm
0,guangzhou,04_2025,11.1,34.4,23.701667,1.917778,28625.190667,5.643333
1,guangzhou,01_2024,2.6,27.3,15.934543,1.029368,24156.993548,0.519355
2,guangzhou,07_2023,24.7,37.2,29.451882,2.272581,38641.818710,6.929032
3,guangzhou,11_2024,11.0,31.0,21.565000,1.179306,27433.607000,1.593333
4,guangzhou,12_2024,8.2,27.3,16.397984,1.156788,31395.129032,0.006452
5,guangzhou,10_2023,16.7,32.9,24.435887,1.321102,25160.991935,6.280645
6,guangzhou,06_2024,22.8,33.7,27.835000,1.665833,25498.888333,15.066667
7,guangzhou,01_2025,7.7,25.2,16.672177,1.326815,34488.539032,0.087097
8,guangzhou,04_2024,18.9,32.0,25.037222,1.549097,19949.846000,23.503333
9,guangzhou,11_2023,11.8,29.5,21.085694,1.317569,30016.323333,0.600000

In [6]:
dfs = [l3y_avg_df, monthly_by_year_df]

for i in dfs:
    print(f"Checking data for DataFrame: {i.shape[0]} rows")
    weather_data = i
    print(weather_data.describe())
    print("------")
    print(weather_data.shape)
    print("------")
    print(weather_data.isnull().sum())
    print("------")
    print(weather_data.info())
    print("------")
    print(weather_data['city'].unique())
    print("------")

Checking data for DataFrame: 60 rows
           month  min_temperature_celsius  max_temperature_celsius  \
count  60.000000                60.000000                60.000000
mean    6.500000                14.340000                32.846667
std     3.481184                 9.514008                 5.434774
min     1.000000                -6.800000                14.900000
25%     3.750000                 6.950000                30.275000
50%     6.500000                17.800000                34.350000
75%     9.250000                22.500000                36.400000
max    12.000000                24.300000                41.300000

       avg_temperature_celsius  avg_uv_index  avg_daily_sunshine_seconds  \
count                60.000000     60.000000                   60.000000
mean                 22.524505      1.630024                30192.565134
std                   7.364756      0.457413                 6053.459103
min                   5.208692      0.639919                15986.856694
25%                  18.295297      1.290350                25783.988167
50%                  26.504739      1.715009                29271.318414
75%                  27.846859      2.017798                35128.258118
max                  30.209005      2.348819                42707.382889

       avg_daily_rainfall_mm
count              60.000000
mean                4.914258
std                 4.842918
min                 0.003226
25%                 1.848301
50%                 3.375556
75%                 6.936492
max                26.542742
------
(60, 8)
------
city                          0
month                         0
min_temperature_celsius       0
max_temperature_celsius       0
avg_temperature_celsius       0
avg_uv_index                  0
avg_daily_sunshine_seconds    0
avg_daily_rainfall_mm         0
dtype: int64
------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   city                        60 non-null     object
 1   month                       60 non-null     int64
 2   min_temperature_celsius     60 non-null     float64
 3   max_temperature_celsius     60 non-null     float64
 4   avg_temperature_celsius     60 non-null     float64
 5   avg_uv_index                60 non-null     float64
 6   avg_daily_sunshine_seconds  60 non-null     float64
 7   avg_daily_rainfall_mm       60 non-null     float64
dtypes: float64(6), int64(1), object(1)
memory usage: 3.9+ KB
None
------
['guangzhou' 'jakarta' 'mumbai' 'shanghai' 'tokyo']
------
Checking data for DataFrame: 185 rows
       min_temperature_celsius  max_temperature_celsius  \
count               185.000000               185.000000
mean                 15.823243                31.502703
std                   9.077478                 5.683504
min                  -6.800000                13.500000
25%                   9.100000                29.500000
50%                  19.900000                33.200000
75%                  23.100000                35.500000
max                  27.000000                41.300000

       avg_temperature_celsius  avg_uv_index  avg_daily_sunshine_seconds  \
count               185.000000    185.000000                  185.000000
mean                 22.674055      1.637857                30200.824744
std                   7.317484      0.469042                 6795.634477
min                   4.696102      0.599597                 9456.629032
25%                  18.873925      1.317569                25565.258065
50%                  26.414286      1.688125                29749.524333
75%                  27.803194      2.009073                35660.232258
max                  31.091263      2.533266                42839.593000

       avg_daily_rainfall_mm
count             185.000000
mean                5.035073
std                 5.893002
min                 0.000000
25%                 0.928571
50%                 3.316129
75%                 6.700000
max                36.700000
------
(185, 8)
------
city                          0
month_year                    0
min_temperature_celsius       0
max_temperature_celsius       0
avg_temperature_celsius       0
avg_uv_index                  0
avg_daily_sunshine_seconds    0
avg_daily_rainfall_mm         0
dtype: int64
------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   city                        185 non-null    object
 1   month_year                  185 non-null    object
 2   min_temperature_celsius     185 non-null    float64
 3   max_temperature_celsius     185 non-null    float64
 4   avg_temperature_celsius     185 non-null    float64
 5   avg_uv_index                185 non-null    float64
 6   avg_daily_sunshine_seconds  185 non-null    float64
 7   avg_daily_rainfall_mm       185 non-null    float64
dtypes: float64(6), object(2)
memory usage: 11.7+ KB
None
------
['guangzhou' 'jakarta' 'mumbai' 'shanghai' 'tokyo']
------