In [1]:
from dotenv import load_dotenv
import boto3
from pathlib import Path
import pandas as pd

load_dotenv()  # reads .env, sets env variables

s3 = boto3.client("s3")
bucket_name = "weather-data-eng" #bucket_name

cities_df = pd.read_csv(s3.get_object(
    Bucket=bucket_name,
    Key="silver/reference/cities.csv")['Body'])

In [2]:
cities_df

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6850,139.7514,Japan,JP,JPN,Tōkyō,primary,39105000.0,1392685764
1,Jakarta,Jakarta,-6.1753,106.8269,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077
2,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133
3,Mumbai,Mumbai,19.0758,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1356226629
4,Shanghai,Shanghai,31.2325,121.4692,China,CN,CHN,Shanghai,admin,24870895.0,1156073548
5,Mexico City,Mexico City,19.3538,-99.1359,Mexico,MX,MEX,Ciudad de México,primary,23146802.0,1484247881
6,São Paulo,Sao Paulo,-23.5504,-46.6339,Brazil,BR,BRA,São Paulo,admin,23086000.0,1076532519
7,Seoul,Seoul,37.5600,126.9900,"Korea, South",KR,KOR,Seoul,primary,23016000.0,1410836482
8,Chongqing,Chongqing,29.5500,106.5069,China,CN,CHN,Chongqing,admin,22251500.0,1156936556
9,Beijing,Beijing,39.9040,116.4075,China,CN,CHN,Beijing,primary,21893095.0,1156228865
10,Kolkāta,Kolkata,22.5675,88.3700,India,IN,IND,West Bengal,admin,21747000.0,1356060520
11,Cairo,Cairo,30.0444,31.2358,Egypt,EG,EGY,Al Qāhirah,primary,20296000.0,1818253931
12,Karachi,Karachi,24.8600,67.0100,Pakistan,PK,PAK,Sindh,admin,20249000.0,1586129469
13,New York,New York,40.6943,-73.9249,United States,US,USA,New York,NaN,19268388.0,1840034016
14,Dhaka,Dhaka,23.7289,90.3944,Bangladesh,BD,BGD,Dhaka,primary,19134000.0,1050529279
15,Moscow,Moscow,55.7506,37.6175,Russia,RU,RUS,Moskovskaya Oblast’,primary,19100000.0,1643318494
16,Bangkok,Bangkok,13.7500,100.5167,Thailand,TH,THA,Krung Thep Maha Nakhon,primary,18007000.0,1764068610
17,Lagos,Lagos,6.4561,3.3936,Nigeria,NG,NGA,Lagos,minor,16637000.0,1566593751
18,Chengdu,Chengdu,30.6600,104.0633,China,CN,CHN,Sichuan,admin,16492980.0,1156421555
19,Delhi,Delhi,28.6600,77.2300,India,IN,IND,Delhi,admin,16349831.0,1356872604
20,Kinshasa,Kinshasa,-4.3233,15.3081,Congo (Kinshasa),CD,COD,Kinshasa,primary,16316000.0,1180000363
21,Istanbul,Istanbul,41.0100,28.9603,Turkey,TR,TUR,İstanbul,admin,15382791.0,1792756324
22,Ho Chi Minh City,Ho Chi Minh City,10.7756,106.7019,Vietnam,VN,VNM,Hồ Chí Minh,admin,15136000.0,1704774326
23,Ōsaka,Osaka,34.6938,135.5021,Japan,JP,JPN,Ōsaka,admin,15126000.0,1392419823
24,Shenzhen,Shenzhen,22.5467,114.0544,China,CN,CHN,Guangdong,minor,14678000.0,1156158707
25,Tehran,Tehran,35.6889,51.3897,Iran,IR,IRN,Fārs,primary,14148000.0,1364305026
26,Buenos Aires,Buenos Aires,-34.5997,-58.3819,Argentina,AR,ARG,"Buenos Aires, Ciudad Autónoma de",primary,13971006.0,1032717330
27,Tianjin,Tianjin,39.1467,117.2056,China,CN,CHN,Tianjin,admin,13866009.0,1156174046
28,Manila,Manila,14.5958,120.9772,Philippines,PH,PHL,Manila,primary,13484482.0,1608618140
29,Lahore,Lahore,31.5497,74.3436,Pakistan,PK,PAK,Punjab,admin,13004135.0,1586801463
30,Wuhan,Wuhan,30.5950,114.2975,China,CN,CHN,Hubei,admin,12447718.0,1156117184
31,Chennai,Chennai,13.0825,80.2750,India,IN,IND,Tamil Nādu,admin,12395000.0,1356374944
32,Los Angeles,Los Angeles,34.1141,-118.4068,United States,US,USA,California,NaN,11984083.0,1840020491
33,Xi’an,Xi'an,34.2611,108.9422,China,CN,CHN,Shaanxi,admin,11904805.0,1156244079
34,Rio de Janeiro,Rio de Janeiro,-22.9111,-43.2056,Brazil,BR,BRA,Rio de Janeiro,admin,11616000.0,1076887657
35,London,London,51.5072,-0.1275,United Kingdom,GB,GBR,"London, City of",primary,11262000.0,1826645935
36,Paris,Paris,48.8567,2.3522,France,FR,FRA,Île-de-France,primary,11060000.0,1250015082
37,Dongguan,Dongguan,23.0475,113.7493,China,CN,CHN,Guangdong,minor,10570800.0,1156478242
38,Bangalore,Bangalore,12.9791,77.5913,India,IN,IND,Karnātaka,admin,10456000.0,1356410365
39,Lima,Lima,-12.0600,-77.0375,Peru,PE,PER,Lima,primary,9751717.0,1604728603
40,Nanjing,Nanjing,32.0608,118.7789,China,CN,CHN,Jiangsu,admin,9341685.0,1156644065
41,Ahmedabad,Ahmedabad,23.0219,72.5797,India,IN,IND,Gujarāt,minor,9272670.0,1356304381
42,Nagoya,Nagoya,35.1814,136.9064,Japan,JP,JPN,Aichi,admin,9197000.0,1392407472
43,Luanda,Luanda,-8.8383,13.2344,Angola,AO,AGO,Luanda,primary,9051000.0,1024949724
44,Foshan,Foshan,23.0292,113.1056,China,CN,CHN,Guangdong,minor,9042500.0,1156738403
45,Chicago,Chicago,41.8375,-87.6866,United States,US,USA,Illinois,NaN,8609571.0,1840000494
46,Taoyuan District,Taoyuan District,24.9913,121.3143,Taiwan,TW,TWN,Taoyuan,admin,8535000.0,1158127875
47,Kuala Lumpur,Kuala Lumpur,3.1478,101.6953,Malaysia,MY,MYS,Kuala Lumpur,primary,8430775.0,1458988644
48,Jinan,Jinan,36.6667,116.9833,China,CN,CHN,Shandong,admin,8352574.0,1156972469
49,Pune,Pune,18.5211,73.8553,India,IN,IND,Mahārāshtra,NaN,8231000.0,1356081074

In [3]:
cities_df.describe()

             lat         lng    population            id
count  50.000000   50.000000  5.000000e+01  5.000000e+01
mean   22.342258   60.589674  1.593888e+07  1.373138e+09
std    19.406228   71.063958  6.747062e+06  2.498091e+08
min   -34.599700 -118.406800  8.231000e+06  1.024950e+09
25%    13.961450   18.721150  1.069310e+07  1.156436e+09
50%    24.925650   84.322500  1.441300e+07  1.356340e+09
75%    35.059500  113.978125  2.000385e+07  1.581246e+09
max    55.750600  139.751400  3.910500e+07  1.840034e+09