In [5]:
import requests
from dotenv import load_dotenv
import boto3
from pathlib import Path
import pandas as pd
import json

load_dotenv()  # reads .env, sets env variables

s3 = boto3.client("s3")
bucket_name = "weather-data-eng" #bucket_name

weather_data = pd.read_csv(s3.get_object(
            Bucket=bucket_name,
            Key="silver/weather/daily_data.csv")['Body'])


weather_data.head(20)

,city,date,month,month_year,daily_sunshine_seconds,daily_avg_temperature,daily_max_temperature,daily_min_temperature,daily_rain,daily_avg_uv
0,guangzhou,2023-07-01,7,07_2023,39807.04,29.054167,33.0,26.3,9.0,7.75
1,guangzhou,2023-07-02,7,07_2023,19721.40,27.425000,30.4,25.4,24.2,7.20
2,guangzhou,2023-07-03,7,07_2023,38057.35,27.595833,31.4,24.7,9.3,8.85
3,guangzhou,2023-07-04,7,07_2023,39177.49,27.737500,32.0,26.1,18.4,8.55
4,guangzhou,2023-07-05,7,07_2023,46800.00,29.545833,33.3,26.1,0.5,9.05
5,guangzhou,2023-07-06,7,07_2023,46800.00,29.683333,33.8,26.2,0.7,9.05
6,guangzhou,2023-07-07,7,07_2023,46800.00,29.833333,34.0,25.9,0.1,9.00
7,guangzhou,2023-07-08,7,07_2023,46800.00,29.966667,34.0,26.4,0.6,9.05
8,guangzhou,2023-07-09,7,07_2023,46800.00,29.683333,33.4,26.5,2.4,9.00
9,guangzhou,2023-07-10,7,07_2023,46800.00,30.420833,34.2,26.6,0.3,8.75
10,guangzhou,2023-07-11,7,07_2023,46800.00,30.400000,34.0,26.7,0.0,9.00
11,guangzhou,2023-07-12,7,07_2023,46800.00,30.395833,34.5,26.2,0.0,9.00
12,guangzhou,2023-07-13,7,07_2023,46800.00,30.229167,34.2,26.2,0.0,9.00
13,guangzhou,2023-07-14,7,07_2023,46800.00,31.454167,35.5,27.3,0.0,8.65
14,guangzhou,2023-07-15,7,07_2023,46432.59,32.345833,37.2,27.3,0.1,9.10
15,guangzhou,2023-07-16,7,07_2023,32330.99,29.412500,34.9,27.5,24.3,7.50
16,guangzhou,2023-07-17,7,07_2023,2433.59,26.554167,28.8,24.8,47.0,3.95
17,guangzhou,2023-07-18,7,07_2023,6660.47,26.820833,29.2,25.4,26.4,7.10
18,guangzhou,2023-07-19,7,07_2023,19272.64,27.420833,30.4,25.7,7.5,8.30
19,guangzhou,2023-07-20,7,07_2023,41877.48,28.766667,32.3,26.2,7.9,5.90

In [4]:
weather_data.describe()

,month,daily_sunshine_seconds,daily_avg_temperature,daily_max_temperature,daily_min_temperature,daily_rain,daily_avg_uv
count,5635.000000,5635.000000,5635.000000,5635.000000,5635.000000,5635.000000,5635.000000
mean,6.535049,30218.195443,22.700245,26.911233,19.313345,5.040976,6.401996
std,3.402421,13120.631409,7.627029,7.766280,7.893217,11.155111,2.146521
min,1.000000,0.000000,-4.366667,-1.600000,-6.800000,0.000000,0.300000
25%,4.000000,23939.285000,18.541667,23.000000,14.700000,0.000000,5.200000
50%,7.000000,35365.110000,26.266667,29.700000,23.100000,0.400000,7.000000
75%,9.000000,39685.265000,27.883333,32.500000,24.900000,5.000000,8.000000
max,12.000000,49423.140000,35.233333,41.300000,31.600000,153.200000,9.650000

In [8]:
print(weather_data.shape)
print(weather_data.isnull().sum())

(5635, 10)
city                      0
date                      0
month                     0
month_year                0
daily_sunshine_seconds    0
daily_avg_temperature     0
daily_max_temperature     0
daily_min_temperature     0
daily_rain                0
daily_avg_uv              0
dtype: int64

In [9]:
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5635 entries, 0 to 5634
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   city                    5635 non-null   object
 1   date                    5635 non-null   object
 2   month                   5635 non-null   int64
 3   month_year              5635 non-null   object
 4   daily_sunshine_seconds  5635 non-null   float64
 5   daily_avg_temperature   5635 non-null   float64
 6   daily_max_temperature   5635 non-null   float64
 7   daily_min_temperature   5635 non-null   float64
 8   daily_rain              5635 non-null   float64
 9   daily_avg_uv            5635 non-null   float64
dtypes: float64(6), int64(1), object(3)
memory usage: 440.4+ KB

In [12]:
weather_data['city'].unique()

array(['guangzhou', 'jakarta', 'mumbai', 'shanghai', 'tokyo'],
      dtype=object)