In [1]:
import requests
from dotenv import load_dotenv
import boto3
from pathlib import Path
import pandas as pd
import json

load_dotenv()  # reads .env, sets env variables

s3 = boto3.client("s3")
bucket_name = "weather-data-eng" #bucket_name

activities_data = pd.read_csv(s3.get_object(
            Bucket=bucket_name,
            Key="silver/activities/activities_data.csv")['Body'])


activities_data.head(20)

,id,city,name,feature,dist,rate,kinds,lat,lon
0,W51811743,guangzhou,People's Park,Feature,99.415259,3,"urban_environment,gardens_and_parks,cultural,i...",23.130188,113.259049
1,N4258606482,guangzhou,广州原点,Feature,163.945015,2,"historic,monuments_and_memorials,interesting_p...",23.128857,113.258987
2,N5029899501,guangzhou,Department of Finance of Guangdong Province,Feature,358.474138,3,"other,unclassified_objects,interesting_places,...",23.130436,113.263466
3,N2920530014,guangzhou,千年古楼遗址,Feature,428.668104,2,"architecture,historic_architecture,interesting...",23.127922,113.263535
4,W288494693,guangzhou,Archaeological Site Museum of Nanyue Palace,Feature,454.877203,3,"historic,archaeology,cultural,museums,interest...",23.129606,113.264420
5,W146674383,guangzhou,Six Banyan tree Flower pagoda,Feature,549.620645,7,"towers,religion,architecture,buddhist_temples,...",23.130945,113.254730
6,W146674393,guangzhou,Temple of the Six Banyan Trees,Feature,562.639736,7,"religion,buddhist_temples,interesting_places",23.130446,113.254524
7,W288492198,guangzhou,Beijing Road Pedestrian Street,Feature,587.822882,2,"cultural,urban_environment,interesting_places,...",23.125854,113.263588
8,W288492189,guangzhou,City God Temple,Feature,596.159093,3,"religion,other_temples,interesting_places",23.129494,113.265793
9,N4221460719,guangzhou,Archaeological Site of the Wooden Watergate of...,Feature,607.873537,7,"historic,archaeology,interesting_places,other_...",23.124840,113.262024
10,W299671419,guangzhou,Big Buddha Temple,Feature,623.230029,3,"religion,buddhist_temples,interesting_places",23.124933,113.262649
11,W613715001,guangzhou,Sun Yat-sen Memorial Hall,Feature,686.511468,3,"historic,monuments_and_memorials,burial_places...",23.136169,113.259346
12,N3037083451,guangzhou,"10,000 Tree Cottage",Feature,702.222887,3,"cultural,museums,interesting_places,other_museums",23.128056,113.266525
13,N5052982060,guangzhou,南海學宮,Feature,767.000291,2,"other,unclassified_objects,interesting_places,...",23.124142,113.256004
14,W582730182,guangzhou,Huaisheng Mosque,Feature,781.500068,7,"religion,mosques,interesting_places",23.125973,113.253738
15,N5344234004,guangzhou,Wing Hon Theatre,Feature,800.536241,2,"cultural,cinemas,theatres_and_entertainments,i...",23.123867,113.264137
16,N5029921054,guangzhou,广州市消防局旧址,Feature,802.301122,3,"other,unclassified_objects,interesting_places,...",23.124439,113.265022
17,W395069470,guangzhou,Sanyuan Palace,Feature,887.211593,7,"religion,other_temples,interesting_places",23.137781,113.257942
18,W361874090,guangzhou,Guangxiao Temple,Feature,907.038950,7,"religion,buddhist_temples,interesting_places",23.131920,113.251389
19,W363576776,guangzhou,Temple of the Five Immortals,Feature,931.407386,3,"religion,other_temples,interesting_places",23.123348,113.254433

In [2]:
print("SHAPE (rows, cols):", activities_data.shape)
print("------")

print("INFO:")
print(activities_data.info())
print("------")

print("DESCRIBE:")
print(activities_data.describe())
print("------")

print("NULL COUNTS:")
print(activities_data.isnull().sum())
print("------")

print("DUPLICATE CITY NAMES:", activities_data['city'].duplicated().sum())
print("------")

print("UNIQUE CITIES:", activities_data['city'].nunique())
print(activities_data['city'].unique())
print("------")

SHAPE (rows, cols): (229, 9)
------
INFO:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 229 entries, 0 to 228
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       229 non-null    object
 1   city     229 non-null    object
 2   name     229 non-null    object
 3   feature  229 non-null    object
 4   dist     229 non-null    float64
 5   rate     229 non-null    int64
 6   kinds    229 non-null    object
 7   lat      229 non-null    float64
 8   lon      229 non-null    float64
dtypes: float64(3), int64(1), object(5)
memory usage: 16.2+ KB
None
------
DESCRIBE:
              dist        rate         lat         lon
count   229.000000  229.000000  229.000000  229.000000
mean   1884.918842    3.768559   20.728442  114.316204
std    1961.094719    1.864645   15.284892   19.604255
min      33.303803    2.000000   -6.204541   72.816834
25%     718.836575    3.000000   19.042772  106.831085
50%    1211.522805    3.000000   23.131191  113.265793
75%    1923.801150    3.000000   31.241129  121.485641
max    9800.481304    7.000000   35.694290  139.761673
------
NULL COUNTS:
id         0
city       0
name       0
feature    0
dist       0
rate       0
kinds      0
lat        0
lon        0
dtype: int64
------
DUPLICATE CITY NAMES: 224
------
UNIQUE CITIES: 5
['guangzhou' 'jakarta' 'mumbai' 'shanghai' 'tokyo']
------

There are duplicates in name / near-duplicate names for the same place (e.g. lines 179 and 182,"Edo Castle" vs "Edo Castle Honmaru").

Cause: OpenTripMap pulls from various sources (src_geom) Tried src_geom=osm  still has dupes (confirms it's an OSM thing, not cross-source), wikidata looks cleaner but has less coverage for smaller cities.

Possible fix: round lat/lon (~3 decimals) and keep highest-rated entry per cluster, since exact name matching won't catch stuff like "Edo Castle" vs "Edo Castle Honmaru".

In [6]:
activities_data.sort_values(['city','rate'], ascending= [False,False]).head(30)

,id,city,name,feature,dist,rate,kinds,lat,lon
184,N5562218658,tokyo,Edo Castle Honmaru Goten Palace,Feature,435.672851,7,"fortifications,historic,interesting_places,oth...",35.688004,139.754501
186,N5409598583,tokyo,Edo Castle,Feature,462.804812,7,"fortifications,historic,interesting_places,cas...",35.688374,139.754410
208,W145400030,tokyo,Sakurada gate,Feature,754.718775,7,"fortifications,defensive_walls,historic,intere...",35.678524,139.753952
219,W43935790,tokyo,Shimizu-mon Gate,Feature,864.292559,7,"fortifications,defensive_walls,historic,intere...",35.692734,139.752564
221,N3949450546,tokyo,Site of MOJ Main Building,Feature,882.172670,7,"architecture,historic_architecture,interesting...",35.677235,139.753494
222,N5350845149,tokyo,Instrument Shelter for Origin of the Japan Ver...,Feature,922.804552,7,"architecture,historic_architecture,interesting...",35.677219,139.747803
224,N5834330376,tokyo,Shimizu Gate,Feature,953.787805,7,"fortifications,historic,interesting_places,oth...",35.693432,139.753448
227,W176046390,tokyo,Tayasu Gate,Feature,1022.705268,7,"fortifications,defensive_walls,historic,intere...",35.694057,139.749298
179,W534754971,tokyo,Imperial Palace,Feature,148.166057,3,"palaces,architecture,historic_architecture,his...",35.683811,139.750656
180,R7676266,tokyo,Tokyo Imperial Palace,Feature,148.166057,3,"palaces,architecture,historic_architecture,int...",35.683811,139.750656
182,R1968066,tokyo,Imperial Palace,Feature,303.623197,3,"palaces,architecture,historic_architecture,int...",35.682339,139.752182
183,W680884178,tokyo,Three Palace Sanctuaries,Feature,368.004298,3,"religion,other_temples,interesting_places",35.681904,139.749939
185,N5808073053,tokyo,Ōoku,Feature,446.876376,3,"architecture,historic_architecture,interesting...",35.687363,139.755402
188,N8354781360,tokyo,Hanzomon,Feature,515.282439,3,"fortifications,historic,interesting_places,oth...",35.683887,139.745880
190,W573270739,tokyo,Hanzo-mon,Feature,540.127956,3,"fortifications,defensive_walls,historic,intere...",35.683758,139.745636
191,W43933152,tokyo,Nijubashi,Feature,553.058588,3,"bridges,architecture,interesting_places,other_...",35.680359,139.753632
192,R5415394,tokyo,Imperial Palace East Gardens,Feature,574.605518,3,"urban_environment,gardens_and_parks,cultural,i...",35.686699,139.757400
193,W43941104,tokyo,Chidorigafuchi,Feature,593.798324,3,"urban_environment,gardens_and_parks,cultural,i...",35.685951,139.744949
195,N4736323978,tokyo,Nijūbashi,Feature,603.563633,3,"view_points,other,interesting_places",35.680260,139.754669
196,N6267045883,tokyo,Chidorigafuchi,Feature,614.118063,3,"cemeteries,historic,burial_places,interesting_...",35.689720,139.747864
197,W43934323,tokyo,National Archives of Japan,Feature,625.248622,3,"cultural,museums,interesting_places,other_museums",35.690262,139.753876
198,N6267046105,tokyo,Hanzō-mon,Feature,652.785005,3,"fortifications,historic,interesting_places,oth...",35.683792,139.744339
199,W43934324,tokyo,"National Museum of Modern Art, Tokyo (MOMAT)",Feature,668.795136,3,"national_museums,cultural,museums,interesting_...",35.690468,139.754517
200,N6267045884,tokyo,Chidorigafuchi National Cemetery,Feature,669.768813,3,"cemeteries,historic,burial_places,interesting_...",35.689514,139.746490
201,N6267046089,tokyo,Chidorigafuchi,Feature,692.826808,3,"cemeteries,historic,burial_places,interesting_...",35.689037,139.745560
202,W870979561,tokyo,Chidorigafuchi National Cemetery,Feature,698.557281,3,"cemeteries,historic,burial_places,interesting_...",35.690125,139.746918
203,R3551876,tokyo,Kitanomaru Park,Feature,716.547803,3,"urban_environment,gardens_and_parks,cultural,i...",35.691460,139.751450
204,N8354781389,tokyo,Kitanomaru-Koen,Feature,718.836575,3,"urban_environment,gardens_and_parks,cultural,i...",35.691471,139.751816
205,W145501856,tokyo,Museum of the Imperial Collections,Feature,729.246746,3,"cultural,museums,interesting_places,art_galleries",35.686523,139.759232
206,W707610674,tokyo,Takebashi Bridge,Feature,741.560751,3,"bridges,architecture,interesting_places,other_...",35.690556,139.755951